notifications:
  email:
    recipients:
      - narenbeniwal3@gmail.com
  on_success: change
  on_failure: always

language: java

jdk:
  - openjdk8

script:
    # JaCoC  is  used to have code coverage,  agent has to be
    -  mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
